domainName :
  - "https://miaxax.com"
  -  "https://miaxos.top"
  - "https://miax68.live"
  -  "https://miaxdf.top"
  -  "https://miaxov.top"
  -  "https://miaxcz.top"
  - "https://tgxhiz.top"
  -  "https://miaxgc.top"
  -  "https://miaxcr.top"
groupID: -913311315
botToken : "6204721569:AAHo1O_QUnDUfGQ1ZxaUEIAC4B1DBymdouQ"